version: '3.8'

services:
  app:
    image: lukevella/rallly:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
    networks:
      proxy_apps:
      default:

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      default:
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true