name: Build and Push Docker image

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Clone external repository
        run: git clone https://github.com/lukevella/rallly.git && cd rallly && find .

      - name: Get the latest tag name
        id: get_tag
        run: echo "APP_VERSION=$(git -C rallly describe --tags $(git -C rallly rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./rallly/apps/web/Dockerfile
          tags: ghcr.io/hueske-digital/rallly:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            SELF_HOSTED=true
            APP_VERSION=${{ env.APP_VERSION }}

      - name: Do not automatically disable workflow execution
        uses: gautamkrishnar/keepalive-workflow@v1